receivers:
  otlp:
    protocols:
      grpc:

exporters:
  # Data sources: metrics
  prometheus:
    endpoint: prometheus:9090
    namespace: default

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]